"""Add extension user support — ext_user_id + linked_telegram_id

Revision ID: 003_extension_users
Revises: 002_whop_deepseek
Create Date: 2026-04-26

Allows browser extension users to optionally link their Telegram account
so their personal RAGFlow rules apply to screenshot analyses.
"""
from alembic import op
import sqlalchemy as sa

revision      = "003_extension_users"
down_revision = "002_whop_deepseek"
branch_labels = None
depends_on    = None


def upgrade() -> None:
    # Extension user identifier (generated by extension, stored in chrome.storage)
    op.add_column("users", sa.Column(
        "ext_user_id", sa.String(64), nullable=True
    ))
    op.create_index("ix_users_ext_user_id", "users", ["ext_user_id"], unique=True)

    # Allow extension users to link their Telegram ID after the fact
    op.add_column("users", sa.Column(
        "linked_telegram_id", sa.BigInteger, nullable=True
    ))

    # Track which product each validation came from more precisely
    # (product is already an int 1/2/3 — add a source field for extension vs bot)
    op.add_column("validations", sa.Column(
        "source", sa.String(20), nullable=True, server_default="telegram"
        # values: telegram | extension | indicator_webhook | ea_webhook
    ))


def downgrade() -> None:
    op.drop_column("validations", "source")
    op.drop_column("users", "linked_telegram_id")
    op.drop_index("ix_users_ext_user_id", table_name="users")
    op.drop_column("users", "ext_user_id")
